apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: loki
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-wal
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info

    common:
      instance_addr: 0.0.0.0
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
        cache_ttl: 24h
        resync_interval: 5s
      filesystem:
        directory: /loki/chunks

    ingester:
      wal:
        enabled: true
        dir: /loki/wal
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    compactor:
      working_directory: /loki/compactor
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      delete_request_store: filesystem

    limits_config:
      retention_period: 168h
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      allow_structured_metadata: true

    querier:
      max_concurrent: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsUser: 10001
      containers:
        - name: loki
          image: grafana/loki:3.1.1
          args:
            - "-config.file=/etc/loki/config/config.yaml"
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 30
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: wal
              mountPath: /loki/wal
            - name: storage
              mountPath: /loki/chunks
            - name: index
              mountPath: /loki/tsdb-index
            - name: compactor
              mountPath: /loki/compactor
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: wal
          persistentVolumeClaim:
            claimName: loki-wal
        - name: storage
          emptyDir: {}
        - name: index
          emptyDir: {}
        - name: compactor
          emptyDir: {}