apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        args:
          - "-config.file=/etc/loki/local-config.yaml"
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki/local-config.yaml
          subPath: local-config.yaml
        - name: wal
          mountPath: /wal
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
      - name: wal
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  local-config.yaml: |
    server:
      http_listen_port: 3100

    ingester:
      wal:
        enabled: true
        dir: /wal
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /tmp/loki/index
        cache_location: /tmp/loki/cache
        shared_store: filesystem
      filesystem:
        directory: /tmp/loki/chunks

    compactor:
      working_directory: /tmp/loki/compactor
      shared_store: filesystem

    limits_config:
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_cache_freshness_per_query: 10m

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

    querier:
      max_concurrent: 20

    query_range:
      parallelise_shardable_queries: true

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true

    frontend_worker:
      frontend_address: 127.0.0.1:9095

    query_scheduler:
      max_outstanding_requests_per_tenant: 100
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app: loki
  ports:
  - name: http
    port: 3100
    targetPort: 3100
