---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-wal
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.1.1
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/config/config.yaml"
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 768Mi
            limits:
              cpu: 1
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: wal
              mountPath: /loki/wal
            - name: chunks
              mountPath: /loki/chunks
            - name: index
              mountPath: /loki/tsdb-index
            - name: compactor
              mountPath: /loki/compactor

      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: wal
          persistentVolumeClaim:
            claimName: loki-wal
        - name: chunks
          emptyDir: {}
        - name: index
          emptyDir: {}
        - name: compactor
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info

    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
        cache_ttl: 24h
        resync_interval: 5s
      filesystem:
        directory: /loki/chunks

    ingester:
      wal:
        enabled: true
        dir: /loki/wal
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    compactor:
      working_directory: /loki/compactor
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      delete_request_store: filesystem
      delete_request_store_key_prefix: compactor/delete-requests/


    limits_config:
      retention_period: 168h
      ingestion_rate_mb: 15
      ingestion_burst_size_mb: 30
      max_query_length: 720h
      max_query_parallelism: 8
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    querier:
      max_concurrent: 20

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    ruler:
      enable_api: true
      storage:
        type: local
        local:
          directory: /loki/rules

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
